export { default as HomeHero } from './hero'
export { default as HomePopularProgram } from './popular-programs'
export { default as HomeFeature } from './feature'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurCoachs } from './coachs'
export { default as HomeNewsLetter } from './newsletter'
