import type { Program } from '@/interfaces/program';

export const data: Array<Program> = [
  {
    id: 1,
    cover: '/images/courses/course1.jpg',
    title: 'Lorem ipsum dolor',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/course2.jpg',
    title: 'Lorem ipsum dolor',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/course3.jpg',
    title: 'Lorem ipsum dolor',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/course4.jpg',
    title: 'Lorem ipsum dolor',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/course5.jpg',
    title: 'Lorem ipsum dolor',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/course6.jpg',
    title: 'Lorem ipsum dolor',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/course7.jpg',
    title: 'Lorem ipsum dolor',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
];
